services:
  - type: web
    name: save-hospital-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: YOUR_MONGODB_CONNECTION_STRING